package hardware

import (
	"fmt"
	"sync"
	"time"

	"go.uber.org/zap"
)

// DMAFaultEvent represents an IOMMU translation page fault generated by a peripheral.
type DMAFaultEvent struct {
	DeviceBDF  string    `json:"device_bdf"`
	FaultAddr  uint64    `json:"fault_addr"`
	FaultType  string    `json:"fault_type"` // e.g., "read_unmapped", "write_unmapped"
	Timestamp  time.Time `json:"timestamp"`
	Throttled  bool      `json:"throttled"`
	Poisoned   bool      `json:"poisoned"`
}

// DMAFaultThrottler tracks per-device DMA page faults and trips poison traps on anomalous probing.
type DMAFaultThrottler struct {
	logger           *zap.Logger
	mu               sync.Mutex
	faultThreshold   int           // max faults within window before throttling
	poisonThreshold  int           // max faults before hardware poison trip
	windowDuration   time.Duration
	deviceFaults     map[string][]time.Time
	isolatedDevices  map[string]bool
}

// NewDMAFaultThrottler initializes the IOMMU DMA fault monitor.
func NewDMAFaultThrottler(logger *zap.Logger, faultThreshold, poisonThreshold int, windowDuration time.Duration) *DMAFaultThrottler {
	if faultThreshold <= 0 {
		faultThreshold = 5
	}
	if poisonThreshold <= 0 {
		poisonThreshold = 10
	}
	if windowDuration <= 0 {
		windowDuration = time.Second
	}
	return &DMAFaultThrottler{
		logger:          logger,
		faultThreshold:  faultThreshold,
		poisonThreshold: poisonThreshold,
		windowDuration:  windowDuration,
		deviceFaults:    make(map[string][]time.Time),
		isolatedDevices: make(map[string]bool),
	}
}

// RecordDMAFault processes an IOMMU fault and returns whether the device has been throttled or poisoned.
func (t *DMAFaultThrottler) RecordDMAFault(bdf string, faultAddr uint64, faultType string) (*DMAFaultEvent, error) {
	t.mu.Lock()
	defer t.mu.Unlock()

	if t.isolatedDevices[bdf] {
		return &DMAFaultEvent{
			DeviceBDF: bdf,
			FaultAddr: faultAddr,
			FaultType: faultType,
			Timestamp: time.Now(),
			Throttled: true,
			Poisoned:  true,
		}, fmt.Errorf("device %s is poisoned and permanently isolated", bdf)
	}

	now := time.Now()
	cutoff := now.Add(-t.windowDuration)

	// Filter timestamps within window
	var recent []time.Time
	for _, ts := range t.deviceFaults[bdf] {
		if ts.After(cutoff) {
			recent = append(recent, ts)
		}
	}
	recent = append(recent, now)
	t.deviceFaults[bdf] = recent

	event := &DMAFaultEvent{
		DeviceBDF: bdf,
		FaultAddr: faultAddr,
		FaultType: faultType,
		Timestamp: now,
	}

	count := len(recent)
	if count >= t.poisonThreshold {
		event.Throttled = true
		event.Poisoned = true
		t.isolatedDevices[bdf] = true
		t.logger.Error("DMAFaultThrottler: Peripheral triggered IOMMU POISON TRAP! Device completely isolated",
			zap.String("device_bdf", bdf),
			zap.Uint64("fault_addr", faultAddr),
			zap.Int("fault_count", count),
		)
		return event, fmt.Errorf("device %s tripped poison trap and was disabled", bdf)
	}

	if count >= t.faultThreshold {
		event.Throttled = true
		t.logger.Warn("DMAFaultThrottler: Peripheral exceeding DMA fault rate, throttling IOMMU requests",
			zap.String("device_bdf", bdf),
			zap.Int("fault_count", count),
		)
	}

	return event, nil
}

// IsDevicePoisoned returns whether the device is permanently isolated.
func (t *DMAFaultThrottler) IsDevicePoisoned(bdf string) bool {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.isolatedDevices[bdf]
}
